feat: Add web support to example app
nayanAubie/msal_auth pull request #62
Opened 2024-12-04 12:49 UTC by Peetee06

This PR adds web support to the example app. The `whenRequired` prompt does not work on web. I used `login` for testing.

It uses a popup based authentication. I didn't test the redirect flow yet, because that needs more adjustments to the example app.

This PR builds on top of #61. Please merge that one first to see the correct diffs here.

2025-02-10 11:53 UTC, nayanAubie commented
@Peetee06 Please rebase this PR

2025-02-10 13:42 UTC, Peetee06 commented
@nayanAubie rebased 🚀

2025-02-11 10:26 UTC, nayanAubie commented on example/lib/environment.dart
> +  static const webRedirectUri = String.fromEnvironment('WEB_REDIRECT_URL');
WEB_REDIRECT_URL > WEB_REDIRECT_URI

2025-02-11 10:29 UTC, nayanAubie commented on example/lib/core/msal_auth_service.dart
> +      tenant: Environment.aadTenantId,
This tenant should not be compulsory because it is only required when you use an organization

2025-02-11 10:43 UTC, nayanAubie commented on example/.metadata
Do we require this file in the example? so far this file has not been created in my local

2025-02-11 10:43 UTC, nayanAubie requested changes
Please address my comments

2025-02-14 04:46 UTC, Peetee06 commented on example/.metadata
removed ✅

2025-02-14 04:47 UTC, Peetee06 commented on example/lib/core/msal_auth_service.dart
> +      tenant: Environment.aadTenantId,
I changed the naming of the environment variable to better reflect its purpose:

```
The tenant value in the path of the request can be used to control who can sign into the application. The allowed values are common, organizations, consumers, and tenant identifiers. Or Name of your Azure AD B2C tenant.
```

2025-02-14 04:47 UTC, Peetee06 commented on example/lib/environment.dart
> +  static const webRedirectUri = String.fromEnvironment('WEB_REDIRECT_URL');
Updated ✅

2025-02-14 05:37 UTC, nayanAubie approved these changes

2025-02-14 05:38 UTC, merged